name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      # 静的解析
      - name: Lint with ktlint
        run: ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true

      # 結果の表示
      - name: Show results on GitHub
        uses: yutailang0119/action-ktlint@v1
        with:
          xml_path: build/ktlint-report.xml

      # アーティファクトへアップロード
      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: results
          path: |
            **/build/ktlint-report.xml
          if-no-files-found: error
          retention-days: 14
  ktlint:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # インストール
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      # 静的解析
      - name: Lint with ktlint
        run: ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true

      # 結果の表示
      - name: Show results on GitHub
        uses: yutailang0119/action-ktlint@v1
        with:
          xml_path: build/ktlint-report.xml

      # アーティファクトへアップロード
      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: results
          path: |
            **/build/ktlint-report.xml
          if-no-files-found: error
          retention-days: 14
